# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0663e1fccbf4f62ea3899d6c30410d7fd99a80975d0f739d991646b84237ab0d3b608d14d1e73a86fb9cb93db67c6a783e8a7b840525f0d4cf21c5d93804d647

test:
  secret_key_base: c07c3e69ceaa4549399874c275559ab847645698e4318f64cb4aacc74aa89037780731faca0006387620dac893fb5b7e9e2cea668316fdccd35fb2f97d854cce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
